name: build

on:
  pull_request:

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update stable rust
        run: rustup update stable
      - name: Format check
        run: 	cargo fmt --all -- --check
  
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update stable rust
        run: rustup update stable
      - name: Lint check
        run: 	cargo clippy

  tests:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
    - uses: actions/checkout@v3
    - name: Update stable rust
      run: rustup update stable
    - name: Run tests
      run: 	cargo test
  